### ISSUE TITLE
pn2a relies on dust

### ISSUE THREAD

**Issue by nehaniv** [egri-nagy/pn2a#1]
pn2a doesn't load due to dependency on dust

**Comment by nehaniv** [comment]
Recently, I had to use gap4r7 and older version of SgpDec to use pn2a.  Would it possible to remove dust dependency easily?

**Comment by egri-nagy** [comment]
I think so. I will try to get to that today.

**Comment by egri-nagy** [comment]
I've just added the missing the data structure from dust and removed dependency. Could you test it?
