### ISSUE TITLE
Add warnings and reasonable behaviour if Boolean condition isn't closed under transitions

### ISSUE THREAD

**Issue by nehaniv** [egri-nagy/pn2a#7]
Add warnings and reasonable behaviour if set of markings satisfying Boolean condition isn't closed under transitions:

(1) options for transition to 'garbage state' if generated marking doesn't satisfy condition
(2) possibly allow reachable states that don't satisfy the condition (rather than state)
(3) currently, there is no checking of the condition if an initial list of markings is specified.

**Comment by erickque** [comment]
`petrinet.initial` is specified
- check if all initial states satisfy condition. if not, give warning but continue
- find all states reachable from initial list
- if a state in initial does not satisfy condition, give warning
- when a new state is found, if condition is not satisfied:
    - go to garbage state if ispartial is specified
    - otherwise, allow those states
- in both cases, give appropriate warning

`petrinet.initial` is empty
- use `petrinet.condition` to set `petrinet.intial` to all possible states that satisfy the condition
- do as above (as if initial is specified)
